services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file: ./.env
    command: sleep infinity
    volumes:
      - ..:/workspaces/logica-core

  db:
    image: postgres:18
    env_file: ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
